# Generated by Django 4.2.6 on 2023-10-15 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access_history',
            old_name='user_Id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='root_Id',
            new_name='root',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='clinic_Id',
            new_name='clinic',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='user_Id',
            new_name='user',
        ),
    ]
