# Generated by Django 4.2.6 on 2023-10-16 21:28

from django.db import migrations
from app.models import User_Root, Customer, Medical_Clinic, Invoice, Access_History

def create_initial_data(apps, schema_editor):
    if Customer.objects.count() == 0:
        Customer.objects.create(
        email='user@gmail.com',
        password='user12345',
        type=1,
        root=User_Root.objects.get(id=1),
    )
    if Medical_Clinic.objects.count() == 0:
        Medical_Clinic.objects.create(
            name='Clinic 1',
            color='red',
        )
    if Invoice.objects.count() == 0:
        Invoice.objects.create(
            invoice_number='1',
            description='Description',
            amount=100,
            title='Title',
            issue_date='2022-01-01',
            due_date='2022-01-01',
            attachment=None,
            reminder=1,
            status='Pending',
            type='Fixed',
            clinic=Medical_Clinic.objects.get(id=1),
            user=Customer.objects.get(id=1),
        )
    if Access_History.objects.count() == 0:
        Access_History.objects.create(
            user=User_Root.objects.get(id=1),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customer_email_alter_invoice_invoice_number_and_more'),
    ]

    operations = [
    ]
