# Generated by Django 4.2.6 on 2023-10-16 21:28

from django.db import migrations, models
from app.models import User_Root, Customer, Medical_Clinic, Invoice, Access_History



class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customer_email_alter_invoice_invoice_number_and_more'),
    ]

    operations = [
        
    ]
