# Generated by Django 4.2.6 on 2023-10-19 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20231016_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='nickname',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.BinaryField(blank=True, max_length='max', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user_root'),
        ),
        migrations.AddField(
            model_name='user_root',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_root',
            name='nickname',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_root',
            name='photo',
            field=models.BinaryField(blank=True, max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='access_history',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user_root'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user_root'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.medical_clinic'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customer'),
        ),
    ]
