# Generated by Django 4.2.6 on 2023-10-26 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('photo', models.BinaryField(blank=True, max_length='max', null=True)),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medical_Clinic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User_Root',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255, unique=True)),
                ('email_root', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('photo', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('amount', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('attachment', models.BinaryField(blank=True, max_length='max', null=True)),
                ('reminder', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.medical_clinic')),
                ('root', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user_root')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user_root'),
        ),
        migrations.CreateModel(
            name='Access_History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user_root')),
            ],
        ),
    ]
