# Generated by Django 4.2.6 on 2023-12-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_access_history_searchable_customer_searchable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='attachment',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_root',
            name='photo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
