# Generated by Django 4.2.6 on 2023-12-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_invoice_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='scheduled_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
