# Generated by Django 4.2.6 on 2024-01-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_access_history_status_alter_access_history_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='access_history',
            name='login_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='access_history',
            name='login_date',
            field=models.DateField(),
        ),
    ]
